CREATE DATABASE StudentManagement
GO

USE StudentManagement
GO

CREATE TABLE Sex(
SeID CHAR(2),
SeName VARCHAR(10),
CONSTRAINT PK_Se PRIMARY KEY (SeID)
)
GO

CREATE TABLE Campus(
CaID NVARCHAR(8),
CaName NVARCHAR(30),
CaAddress NVARCHAR(100),
CaEmail NVARCHAR(30),
CaHotline NVARCHAR(30),
CONSTRAINT PK_Campus PRIMARY KEY (CaID)
)
GO

CREATE TABLE Major(
MaID CHAR(2),
MaName NVARCHAR(100),
CONSTRAINT PK_Major PRIMARY KEY (MaID)
)
GO

CREATE TABLE SPECIALIZATION(
SpID CHAR(2),
SpName NVARCHAR(30),
SpDes TEXT,
MaID CHAR(2),
CONSTRAINT PK_Specialization PRIMARY KEY (SpID),
CONSTRAINT FK_Specialization FOREIGN KEY (MaID) REFERENCES Major(MaID)
)
GO

CREATE TABLE Student(
StID CHAR(8), 
StFName NVARCHAR(30),
StLName NVARCHAR(30),
StSex CHAR(2),
StEmail NVARCHAR(30),
CaID NVARCHAR(8),
SpID CHAR(2),
MaID CHAR(2),
StSemester INT NOT NULL,

)
GO

--USE master
--GO

--DROP DATABASE StudentManagement
--GO
