INSERT INTO Subject(SuID,SuName,SuNoCredit,SuPrerequisite) VALUES 
('OTP101', ' Orientation and General Training Program' , ' 0', ''),
('PEN', ' Preparation English', ' 0', ' '),
('PHE_COM*1', ' Physical Education 1', ' 2', ' '),
('TMI_ELE', ' Traditional musical instrument', ' 3', ' '),
('CEA201', ' Computer Organization and Architecture', ' 3', ' '),
('CSI104', ' Introduction to Computer', ' 3', ' '),
('MAE101', ' Mathematics for Engineering', ' 3', ' '),
('PHE_COM*2', ' Physical Education 2', ' 2', ' '),
('PRF192', ' Programming Fundamentals', ' 3', ' '),
('SSL101c', ' Academic Skills for University Success', ' 3', ' '),
('MAD101', ' Discrete mathematics', ' 3', ' '),
('OSG202', ' Operating Systems', ' 3', ' '),
('PHE_COM*3', ' Physical Education 3', ' 2', ' '),
('PRO192', ' Object-Oriented Programming', ' 3', ' Pass PRF192'),
('SSG104', ' Communication and In-Group Working Skills', ' 3', ' '),
('CSD201', ' Data Structures and Algorithms', ' 3', ' PRO192'),
('DBI202', ' Introduction to Databases', ' 3', ' '),
('JPD113', ' Elementary Japanese 1- A1.1', ' 3', ' '),
('LAB211', ' OOP with Java Lab', ' 3', ' PRO192'),
('JPD123', ' Elementary Japanese 1-A1.2', ' 3', ' JPD113'),
('MAS291', ' Statistics & Probability', ' 3', ' MAE101 or MAC101'),
('PRC391c', ' Cloud Computing', ' 3', ' PRO192'),
('PRJ302', ' Java Web Application Development', ' 3', ' DBI202, PRO192'),
('SWE201c', ' Introduction to Software Engineering', ' 3', ' PRO192 (not applied to the BIT_AI17 and BA programs)'),
('DTA301', ' Data Analysis', ' 3', ' PRO192, CSD201, DBI202, MAS291'),
('ISM302', ' Enterprise Resource Planning (ERP)', ' 3', ' '),
('ISP392', ' Information System Programming Project', ' 3', ' PRJ302, SWE201c'),
('ITA301', ' Information System Design & Analysis', ' 3', ' ITA203c, DBI202'),
('ITE302c', ' Ethics in IT', ' 3', ' None'),
('ENW492c', ' Academic Writing Skills', ' 3', ' '),
('OJT202', ' On-The-Job Training', ' 10', ' Students attain 90% of the total credits from term 1-term 5 (excluding Physical Education and OTP Programs) Students choosing JS combo (Japanese Bridge Engineer) have to pass JPD123'),
('EXE101', ' Experiential Entrepreneurship 1', ' 3', ' '),
('IS_COM*1', ' Subject 1 of Combo*', ' 3', ' '),
('IS_COM*2', ' Subject 2 of Combo*', ' 3', ' '),
('ISC301', ' e-Commerce', ' 3', ' Recommended to take this course after OJT'),
('ITB302c', ' Business Intelligence (BI)', ' 3', ' '),
('EXE201', ' Experiential Entrepreneurship 2', ' 3', ' EXE101'),
('IS_COM*3', ' Subject 3 of Combo*', ' 3', ' '),
('IS_COM*4', ' Subject 4 of Combo*', ' 3', ' '),
('MLN111', ' Philosophy of Marxism', ' 3', ' '),
('MLN122', ' Political economics of Marxism', ' 2', ' '),
('PMG201c', ' Project Management', ' 3', ' None'),
('HCM202', ' HCM Ideology', ' 2', ' MLN111, MLN122'),
('IS_GRA_ELE', ' Graduation Elective - Information System', ' 10', ' '),
('MLN131', ' Scientific socialism', ' 2', ' MLN111, MLN122'),
('VNR202', ' History of CPV', ' 2', ' MLN111, MLN122'),
('NWC204', 'Computer Networking ', '3 ', ' '),
('PRM392','Mobile Programming','3','PRO192'),
('SWP391', 'Software development project', '3', 'PRJ301, SWE201c')
GO